// create js file to delete occurrence of all element in given array
// create js file to delete occurence of elmeent that equal 56

//let arr= [23,56,4,78,5,63,45,210,56];
//const arr_len= arr.length;
//let elm= 56;
//for(let index=0; index< arr_len; index++){
  //  if(arr[index] == elm){arr.splice(index,1)   }
//}

//console/log sth

//write a js code to find the power of a number using for loop
// 4^3=64
//16^2=256

let num = 4;
let pow = 3;
let res= 1;// return for power = 0
// then i ll just to change the number- do loop to change this
for(let i= 0; i < pow; i++){}